export const userTypes = {
    RESTORE_TOKEN: "RESTORE_TOKEN",
    LOGIN: 'LOGIN',
    SIGNUP: 'SIGNUP',
    USER_LOGOUT: 'USER_LOGOUT',
    SAVE_SPOTIFY: 'SAVE_SPOTIFY',
    UPDATE_USER: 'UPDATE_USER',
    ERROR_LOGIN: "ERROR_LOGIN",
    ERROR_SIGNUP: "ERROR_SIGNUP",
    DARK_MODE: "DARK_MODE",
    ERROR_NETWORK: "ERROR_NETWORK"
}