export const userTypes = {
    RESTORE_TOKEN: "RESTORE_TOKEN",
    LOGIN: 'LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',
    SAVE_SPOTIFY: 'SAVE_SPOTIFY',
    SET_ERROR_LOGIN: "SET_ERROR_LOGIN",
    SET_ERROR_SIGNUP: "SET_ERROR_SIGNUP",
    SET_DARK_MODE: "SET_DARK_MODE",
    SET_ERROR_NETWORK: "SET_ERROR_NETWORK",
    SET_ERROR_ACCESS: "SET_ERROR_ACCESS",
    SET_ERROR_EMPTY_MUSIC: "SET_ERROR_EMPTY_MUSIC",
    SET_ERROR_UPDATE: "SET_ERROR_UPDATE",
    SET_ERROR_UPDATE_MESSAGE: "SET_ERROR_UPDATE_MESSAGE"
}